{% set version = "0.33" %}

package:
  name: larray_eurostat
  version: {{ version }}

source:
  url: https://github.com/larray-project/larray_eurostat/archive/{{ version }}.tar.gz
  sha256: e90978f25c745487665c30149f984b857f563c559d6401fff8a16d025388e476

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - larray

test:
  imports:
    - larray_eurostat

about:
  home: http://github.com/larray-project/larray_eurostat
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Additional package to import Eurostat files using LArray
  dev_url: http://github.com/larray-project/larray_eurostat

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
