{% set name = "larray_eurostat" %}
{% set version = "0.27" %}
{% set sha256 = "7509a24ee7048f5be6edaf452a6e4c5d9f4da423daac3cb309eb50c65ab18167" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/larray-project/larray_eurostat/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - larray

test:
  imports:
    - larray_eurostat

about:
  home: http://github.com/larray-project/larray_eurostat
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "Additional package to import Eurostat files using LArray"

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
