{% set version = "0.35.2" %}

package:
  name: larray_eurostat
  version: {{ version }}

source:
  url: https://github.com/larray-project/larray_eurostat/archive/{{ version }}.tar.gz
  sha256: 5efe65c85e3a2d03671dd66f5fb7fcf46e1c782f68ced8f91e309f6abf47efb4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - larray

test:
  requires:
    - python {{ python_min }}
  imports:
    - larray_eurostat

about:
  home: https://github.com/larray-project/larray_eurostat
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Additional package to import Eurostat files using LArray"
  dev_url: https://github.com/larray-project/larray_eurostat

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
