{% set name = "larray_eurostat" %}
{% set version = "0.29" %}
{% set sha256 = "9c0cb3d758a9982a1253d9f749f3308175a00b03a8a8ec368f66b0d4cde73598" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/larray-project/larray_eurostat/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - larray

test:
  imports:
    - larray_eurostat

about:
  home: http://github.com/larray-project/larray_eurostat
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "Additional package to import Eurostat files using LArray"

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
