{% set version = "0.34.1" %}

package:
  name: larray_eurostat
  version: {{ version }}

source:
  url: https://github.com/larray-project/larray_eurostat/archive/{{ version }}.tar.gz
  sha256: b2426e3ad90e2f28316308ebb42931b8930b15c9accaf8b89871945cd71c36d3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - larray

test:
  imports:
    - larray_eurostat

about:
  home: http://github.com/larray-project/larray_eurostat
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Additional package to import Eurostat files using LArray"
  dev_url: http://github.com/larray-project/larray_eurostat

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
