travis:
  secure:
    BINSTAR_TOKEN: a7Bqp1oTyQHTqoYCRn9Xyk5QS9MfLk35LsEIklnGKXWDTjCpcTgxMDsVU0gIecqTEPdxWzl7rhJa0mSMV2hJ/q3RldcUq8W3pZpSJ9qTD5lH+s+1za2NE58JozZsgQCf+/E7aAxBaKLQjSjmYU5mk0mLF466LO723NR6YDewOGXy3XaYs4Nk4sYVVmH0MphMWBJMh3+oXd0O4gmrlr1tr3lfRrKjjjEzKZEl3LvlM51irT5SCZor1eHLib27iau1MLh+vMaRweK/GFj7iBLBMpnOfqpXOqw8rInNb2wwseu7O7XbQ2csoXvUwakiKv2nqCptH6hvSU3rLNT5zwTLNuONwHS0K2cE4v88DjTwg8U+/bwuNHL2Exfr7tTINABWRbQItQhu0e2d0bFhCr4xQ3dpbwP6z/gj++vKTP7yA31P+D9+CRnWNBp4InUbp7zkhFQiztVKmmdnnnWXVM8kqBD/LrZelhK8heAsIJw9s1Fw8xFL8fIfdIsiZ631OkYZEjMT6AwKwrSIEPqbQDZj2w7F1YpvVAukq487fiD5IubjjpYX9F/oOWeord0p3M84ii6hfvLFLVqafDehXeOV+n7KqgCWBEvFFFREqzo8HTGBgl8AI2lKH+OkiLpYes3/Z/rtxDozrDnbEHa+SowHenokoIedSUnq1OQsD0zQ/Qo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
