travis:
  secure:
    BINSTAR_TOKEN: DUvzyYBTsXu9ggA1lfv+RXXwlkvsDURPgpYvgZz0KiVvNjLFq9yi6ZbGGujyBoIj6gJ2sMHdrfuKl6PtiaWXnw+Sxx548oz+ObeTn7+TwtCTMfKfjhHZq+KHl9LsmC46oDQltLWFaNdUNyGQ92PPt61OR0E33j6z1l0N7eqxejvOFT+aUfFKAnfP4ylNgzXOz0BfarpuYyJovbRkFIn1cu8sbFCTXAwr9cAH7XFEYfs9DcmSm91e1Te5UHnasapTjEv5rIpUX1v1dprfDh5IJJP/4rbtVqpBOBFbDj5XkbaemqMVWzP+zByLVSKrW/AgEd0EruGbGia1wmJbBLsZLEB7bUYWCIUS6XfxPM51//IqPSuNPkFaFVu89spBQ3KUGXssiUezjx6xzx170CEV2AJKBOe2vQ8ZruIopc0Cm4fxZCHdGSKYECzfcJiDTloXBOJssxTFGMwy0mdDdOAyF7/Vpcf125wqFvpmUhz+mlynnQ/OApzDUK2w+XcEOun76xAdpnuS7TGyeWO0o+IanhqXlGPLHI3QM+IY3XPBXwvV9olCD0K3UukiMOgiTV9u8M3RoAbJgVDxtL6fqIvyU3uxW1ObUgHS0j4BlllYEy34z5RUvipztwKO266QrjxECCqjeQ0Q87K0Qt0/Cj1ju9sjMcvDxeWgAK0a+KDVWoE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
