travis:
  secure:
    BINSTAR_TOKEN: chDWbbsRhyDNOoNI98d09jRiCBgHf6nVMI7a75XmuXIbaZpJN+Gmn4gLPRCFLZQdErDbvCsyIGv2PeavpiyL7jUojYG7M9n3z506ZOgOxlFOeFOcfW496LxiiGrGBqKf4jbN2kK2VVQ5sSBTs/GUdNDjeOTUFIdiERSCtCfHZ0Dzns7DgGnppVqIgSzohbyTCTopnzLox7m8iqVedel4RKb60vdnfh/mpkcD2mN7Nyo7w/zOh10GA5LYCysnyQBEA9c9Ca8JmWprnnw1YnKEZVB/UlxCcZtZ2ofYR8jN0+jPBNezBA86vcbRlH2FJIGJjseNO4xaqLvTk1sUwJgrif8HLBOMm2kE1ypKbcRF2Go0ww71DRISjdesyhSLbaioR2ZuMdL67B7O8uq98+lT3UXSdXMu84PUYvim+5K78058+dDxluV/F577rW7+qnY0GELDnGZ4be3pfAU8BSLIIDJ2La/qsTaqwZnGIqNgfB/JLNgGIog2IaG0gnvqFtcAqtB9wE0BJUYPwq+GZy57DiFSp/7SmNbbZ/jeIaupUmQd6gEx6DyVtxTTAJRUVlGZW6GlieAjaoW9UZpQM3+WcsBLc+yQB9vo7mLN0RS5nTwLMsOK3cVQvHtqlmbamIVLxRSIhVlmUkn02+5xg+wALdmgZ9BH2cvdvp4Tb5+gysQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
